### ISSUE TITLE
crm_helpdesk_mail_team

### ISSUE THREAD

**Issue by acruzdb** [OCA/helpdesk#10]
### Migration module crm_helpdesk_mail_team from v8 to v11

- The person in charge of this task must do it based on the module crm_helpdesk_mail_team (https://github.com/factorlibre/helpdesk/tree/8.0-FL_Helpdesk_Improvement).

- The relevant changes must be made to update module to v11.

**Comment by pedrobaeza** [comment]
Is this already completed?
