### ISSUE TITLE
Create Ticket from Mail with team alias

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/helpdesk#102]
I understand that by now, the ticket creation from mail is only possible using custom incoming mail server configuration, using the "create record" option.
If you agree, I could expand the ticket.team model by adding the alias logic to create tickets from mail... on the same way that the CRM do it. I think that is better option :)

**Comment by pedrobaeza** [comment]
If not present, yeah, that would be great, but I don't know this part.

**Comment by DarioLodeiros** [comment]
#105
