### ISSUE TITLE
[RFC] Website Form on v13.0

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/helpdesk#107]
I have a doubt with this question on v13... its better to integrate de ticket creation form with the core form editor registry released on 13.0?
Example with recruitment:
https://github.com/OCA/OCB/blob/13.0/addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js#L9

Origin from #106

**Comment by pedrobaeza** [comment]
This is not the migration issue... This one is: #96

**Comment by DarioLodeiros** [comment]
Ou, ok, I understand, Thanks Pedro ;)
