### ISSUE TITLE
crm_helpdesk.py + crm_helpdesk_view.xml

### ISSUE THREAD

**Issue by acruzdb** [OCA/helpdesk#11]
### Migration module crm_helpdesk_states from v8 to v11

- The person in charge of this task must do it based on the module crm_helpdesk_states (https://github.com/factorlibre/helpdesk/tree/8.0-FL_Helpdesk_Improvement).
- The relevant changes must be made to update the model and the view to v11.

 ***It will be necessary to review the way to define the states before performing this task**

**Comment by DaniKL** [comment]
Hello.

About the helpdesk_ticket_stage, we have a module where the different stages are inside a Selection field in 7 default stages, and a series of functions that depends in those default values. Our intent with the 7 default stages is to create certain workflows and functionalities. If there's a need to create new stages, it can be developed apart. 

So what do you think about we make the stages this way so we can migrate our v8 stage functionalities into the v11 base?

**Comment by aitorbouzas** [comment]
Making the stages static would be breaking a big part of what is already done.

Stages should be something dynamic, that was one of the first things we stated from the beginning. If a customer wants to manage different stages than the original ones (the ones that are in the data xml) it means development should be done, and that's not how an OCA module should work. It must be as standard as possible.

If you have a module with several behaviours depending on each stage you should try to integrate them or make them happen with a dynamic envinroment like we did with email sending or marking a ticket as done.

**Comment by DaniKL** [comment]
Ok, so regarding stages transition, should they be automatic depending on certain actions or be changed manually by the user?

Example:
Option 1 (automatic) Ticket 1 is created with the stage "new". It remains "new" until an user is assigned to the ticket, in this moment an email is sent to the assigned user and the ticket changes to "In Progress".
Option 2 (manual) Ticket 2 is created with the stage "new". When an user is assigned, en email is sent, but until that user doesn't change the stage to "In Progress", it remains "New".

Which option would be the best?

**Comment by aitorbouzas** [comment]
Right now option 2 is how this actually works and how it's supposed to work in the base module.
If you want to implement option's 1 behaviour you'll have to make a separate module and try to automate this state change.

**Comment by pedrobaeza** [comment]
Is this already completed?
