### ISSUE TITLE
Question : Installing OCA helpdesk module(v12)

### ISSUE THREAD

**Issue by r3dius** [OCA/helpdesk#116]
hello! This is a simple question but i dont know how to do it. 
How to install OCA Odoo assitance module with my Odoo instance (v12) ? 
Thank you very much.

Reda.

**Comment by pedrobaeza** [comment]
This question is out of the scope of the issue tracker, that it's for issues in the code. Little tip: download the module and put it on your Odoo addons path.

**Comment by r3dius** [comment]
Hello! thank you very much for the tip. I will try this.
Reda.

**Comment by dnrun** [comment]
So frustrating that it doesn't show up. All I see is the paid subscription helpdesk module. Can someone make a docker compose or something
