### ISSUE TITLE
Remove attachment page on Tickets

### ISSUE THREAD

**Issue by EDallas89** [OCA/helpdesk#127]
On module helpdesk_mgmt, on tickets form views, there is a page named attachment that unnecessary.
Its functions are already covered by chatter.

**Comment by eLBati** [comment]
The attachment tab allows a more direct access to attachments, with bigger content preview. I don't think it's useless

**Comment by pedrobaeza** [comment]
I also think it's a useless duplicated feature.

**Comment by gdgellatly** [comment]
Resolved
