### ISSUE TITLE
[12] is helpdesk [12] still an alpha developement state, or it is beta as version [13]?

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/helpdesk#145]
[12] is helpdesk [12] still an alpha developement state, or it is beta as version [13]?

**Comment by DarioLodeiros** [comment]
I am not using this module in production, only at a formative level for courses.
I do not know if @emagdalenaC2i, @samuel-domatix, @oscars8a or someone else can give their opinion about it

**Comment by pedrobaeza** [comment]
It should be beta indeed

**Comment by DarioLodeiros** [comment]
I changed it... by mistake I did it directly instead of using PR :facepalm:  , but if there is no problem I leave it as a maintenance change without implication in the code
https://github.com/OCA/helpdesk/commit/d74110089a406e8c31a8f793f8293f22b374165f

**Comment by pedrobaeza** [comment]
No problem. Indeed it can be a maintenance commit.

**Comment by emagdalenaC2i** [comment]
I have implemented the module and did several tests but have not yet shared it with our customers, so It is not yet used in production. We will migrate to Odoo 13 soon and then we will share with our customers.

But the tests worked fine and I think it should be in beta state
