### ISSUE TITLE
Stages are not clickable from the ticket view

### ISSUE THREAD

**Issue by olivierb2** [OCA/helpdesk#153]
When I display the ticket content, I'm unable to click on stage in order to update the stage status. I need to move back from kanban view. This issue is only for this module, other modules like CRM allow me to update stage from the opportunity view.

Edit : this issue occurs on Odoo 13.

![Stage not clickable](https://user-images.githubusercontent.com/2324018/89032854-d0ead600-d335-11ea-8e18-0f5902ffe852.png)

**Comment by DarioLodeiros** [comment]
have you tried this in the runbot ?, I just tried it in runbot and review the code and I don't see the reason why it doesn't allow you to edit the state in your case

**Comment by olivierb2** [comment]
I'm not sure where or how I can use runbot quickly, but I have two Odoo 13 separate instance with the same problem. I tried to regenerate asset to be sure, but I definitely don't know why I'm getting this issue.

**Comment by olivierb2** [comment]
Small update : I'm not developper, but seems that removing tag `disabled="disabled"` from F12 developer tools re-enable the link. Any reason why those buttons are set as disabled?

![Capture d’écran de 2020-07-31 15-11-32](https://user-images.githubusercontent.com/2324018/89038224-3c39a580-d340-11ea-8250-1931a2aab02d.png)

**Comment by olivierb2** [comment]
I finally helped myself, from developer mode, I changed the form view :

~~~ html
<field name="stage_id" widget="statusbar" clickable="True"/>
~~~

Into

~~~ html
<field name="stage_id" widget="statusbar" options="{'clickable': '1', 'fold_field': 'fold'}"/>
~~~

**Comment by DarioLodeiros** [comment]
Ok, I was looking at v12, remember to indicate version and other data that you see relevant to facilitate the review. Thanks!

**Comment by olivierb2** [comment]
Ho, my bad, apologies, this is a really newbie mistake :D

**Comment by DarioLodeiros** [comment]
Dont worry, Thanks for the issue, should already be resolved if you update the sources :)

**Comment by olivierb2** [comment]
Got it, thanks for you commit !
