### ISSUE TITLE
[12.0] helpdesk_mgmt_timesheet not translatable

### ISSUE THREAD

**Issue by eLBati** [OCA/helpdesk#158]
As not present at https://translation.odoo-community.org/projects/helpdesk-12-0/

**Comment by eLBati** [comment]
@sbidoul do you know why? Thanks

**Comment by dalonsod** [comment]
Any news on this?

**Comment by sbidoul** [comment]
This is now resolved: https://translation.odoo-community.org/projects/helpdesk-12-0/helpdesk-12-0-helpdesk_mgmt_timesheet/

**Comment by eLBati** [comment]
Thanks!
