### ISSUE TITLE
Backend created tickets don't show up in portal

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/helpdesk#159]
If we create a new ticket on the Odoo backend, it won't show on the the associated partner portal view. That's because rule
```
    <!-- Portal for helpdesk -->
    <record id="helpdesk_ticket_rule_portal" model="ir.rule">
        <field name="name">Portal Personal Tickets</field>
        <field name="model_id" ref="model_helpdesk_ticket"/>
        <field name="domain_force">[('message_partner_ids','child_of',[user.commercial_partner_id.id])]</field>
        <field name="groups" eval="[(4, ref('base.group_portal'))]"/>
    </record>
```
only shows tickets on which the partner is a follower. But when the ticket is created on the backend, the partner is not added to the followers list.
I can try to fix this but would appreciate your opinion: should we add the partner to the followers list or modify the portal rule and add an OR clause with ('partner_id','child_of',[user.commercial_partner_id.id])  ?

**Comment by pedrobaeza** [comment]
This works the same as project, suggesting the partner as follower first time you write a message.

**Comment by pedrocs-exo** [comment]
True but that's not the point. When you create a project for a client in the backend, the client is automatically added to the followers list and he can immediately see the project and tasks in the portal (even if no message was sent).

On the backend ticket creation, the client is NOT added as a folllower and so we won't be able to see it in the portal.

**Comment by pedrobaeza** [comment]
AFAIK, the customer is not subscribed in tasks as well.
