### ISSUE TITLE
I don't have access to the public ticket page (web)

### ISSUE THREAD

**Issue by doubledoze** [OCA/helpdesk#169]
Hello,
I will contact you to ask for a little help.

I have installed the helpdesk_mgmt module, I do have access to Helpdesk on the backend, but on my website I don't know how to access the user view to create and track tickets, I don't know the url.

Usually when I install a module, if there is a part on the web, the link is automatically added to the website menu but this is not the case.

Thanks in advance for your help,
Sincerely, Samy

**Comment by DarioLodeiros** [comment]
The helpdesk system is thinking to use on portal user (with partners like project customers), its can be created using mail alias on helpdesk team, or you can user the "/new/ticket" relative url.

**Comment by doubledoze** [comment]
@DarioLodeiros 
Thank you for this information, I understand better.
Are there other url to know ? Maybe a url to display the list of tickets that concern us?

Because I would like my customers when they are connected to the website, can use this url to create tickets, but also access a url to see the list of tickets that concern them.
Thank you.

**Comment by DarioLodeiros** [comment]
You must know how the customer portal works with the rest of the areas of odoo, sales, projects, etc. The helpdesk works with the generic logic of the customer portal (accessing your account from the web or through follow-up emails)
I close the issue but if you have any idea feel free to create a new issue with any proposal ;)
