### ISSUE TITLE
Helpdesk Base

### ISSUE THREAD

**Issue by agent-z28** [OCA/helpdesk#17]
We have a whole set of Modules for helpdesk implemented. Shall we Do a pr and we see what will make it? Or whats the best way now

**Comment by pedrobaeza** [comment]
The problem is that we already have an implementation in progress in #1. Maybe you can review it, and comment differences of your modules with it, and then set a roadmap where technical people can take your source code and add that differences.

**Comment by agent-z28** [comment]
Okay! Great Next Time lets discuss earlier!:)
I try to do it tonight

**Comment by agent-z28** [comment]
I'll submit this tonight:

  1 {
  2     'name': "Helpdesk Timesheet",
  3     'category': 'Helpdesk',
  4     'version': '11.0.1.0.0',
  5     'depends': [
  6         'helpdesk',
  7         'hr_timesheet'
  8     ],
  9     'data': [
 10         'views/helpdesk_view.xml',
 11         'views/hr_timesheet_view.xml',
 12         'views/helpdesk_ticket_stage_view.xml'
 13     ],
 14     'author': 'Agent ERP GmbH'
 15               'Odoo Community Association (OCA)',
 16     'website': 'https://github.com/OCA/helpdesk',
 17     'license': 'AGPL-3',
 18     'installable': True,
 19 }
 
I think its a perfect fit with littl modification!

**Comment by agent-z28** [comment]
done! I suggest a addons module for helpfull improvements.
E.g. We have a "Solution required" field where the user has to describe the solution before he can close the ticket.
Also we have automaticaly sent emails by changing the state of the ticket.
Shall i create a pull request with an extra module or in the main one

**Comment by pedrobaeza** [comment]
But you have put a pull request with your full `helpdesk` module, isn't it? which is competing with current pull request #1. The first one has priority right now over yours. The things to do can be to analyze differences between both and extract interesting features from yours into the first one.

About the sent mails by changing state, that can be easily done through thread tracking mechanism and integrated in main module. Other things can be a bit over-engineered. The only interesting thing that I see can be to link a stage with a mail template (the same as task stages do) for sending that template.

**Comment by agent-z28** [comment]
No, I moved all views to the OCA helpdesk... the module i added is the one from #1.

"The only interesting thing that I see can be to link a stage with a mail template (the same as task stages do) for sending that template." 

yes exactly that is what i am missing. PR for helpdesk or addons module?

**Comment by pedrobaeza** [comment]
Ah, OK, what dazzled me was that you included the same module again in that PR. You would need to rebase your PR after merging the main one then.

**Comment by agent-z28** [comment]
Yes i can rebase it after. What you say about the stage template. Shall we move it into the base module or as addon?

**Comment by pedrobaeza** [comment]
I think that can be an option in base. It's not so much code and it's a basic feature IMO.

**Comment by emagdalenaC2i** [comment]
I think that is already part of the roadmap #12

**Comment by agent-z28** [comment]
but i have one thing to add. when moving in kanban view, the behaviour we want, is that we get a mail-wizard, where we get a "suggestion", but it still can be edited. 
AFAIK this will need small js changes to the kanban view.
What do you think?

**Comment by pedrobaeza** [comment]
I don't think that's a good approach, as it's error prone and anti-automation. The mail template defined at stage level determines if sending the template or not, and also followers subscriptions allow the customization. If not, indeed JS code should be involved for doing that, and with the risk that mail is sent but if an error is raised, the stage is not changed. I would encourage not to do it that way.

**Comment by agent-z28** [comment]
I get your point! But what,
if the closing of a Ticket requires to explain the user something? 
Will you write the via mail_chatter and then change the stage afterward ?
That will make one more click to do and will also envolve mistakes..
Currently i click on Done, get the Wizard and can write final answer e.g.

**Comment by pedrobaeza** [comment]
For the case you mention, the chatter solution is good for me, but you can improve the flow adding a button "Close", that opens a transient model with popup form view (aka wizard) for requesting you a closing text, and when clicking on the wizard, perform both operations.

The wizard will be similar to this module: https://github.com/OCA/sale-workflow/tree/12.0/sale_cancel_reason

**Comment by agent-z28** [comment]
> For the case you mention, the chatter solution is good for me, but you can improve the flow adding a button "Close", that opens a transient model with popup form view (aka wizard) for requesting you a closing text, and when clicking on the wizard, perform both operations.
> 
> The wizard will be similar to this module: https://github.com/OCA/sale-workflow/tree/12.0/sale_cancel_reason

I agree, but if you move in kanban to close, this button wont be clicked. So i was assuming, that the mail wizard would appear anyway. but i can live with this in OCA, i can customize for us.

**Comment by aitorbouzas** [comment]
@agenterp can this be closed? let's keep discussing in #18

**Comment by agent-z28** [comment]
YES of course! will finish the other one this week.
