### ISSUE TITLE
Don't modify timesheet on a closed ticket

### ISSUE THREAD

**Issue by EDallas89** [OCA/helpdesk#176]
On module helpdesk_mgmt_timesheet it shouldn't be possible modify a line from timesheet if ticket is closed.

**Comment by pedrobaeza** [comment]
Why? There are legit cases where you need to input timesheet lines in closed tickets. Requiring to reopen shouldn't be needed. You can, however, improve the module for adding a check at stage level for avoiding timesheeting on that stages and make it configurable.

**Comment by gdgellatly** [comment]
:-1 for me too. There are many legit reasons to do this and no valid reason given here not to allow it. Reopening triggers emails and all sorts.  The obvious counter reason, I closed the ticket, now I need to stop recording my time is a completely valid workflow.
