### ISSUE TITLE
Wrong spelling of 'Helpdesk' (helpdesk 13.0)

### ISSUE THREAD

**Issue by Ramil-Mukhametzyanov** [OCA/helpdesk#181]
Wrong spelling of 'Helpdesk'
![Screenshot from 2020-11-27 17-46-37](https://user-images.githubusercontent.com/33877236/100451168-c1f41480-30d8-11eb-9640-161af9bf09af.png)
Please check

**Comment by gdgellatly** [comment]
@Ramil-Mukhametzyanov thanks for reporting, it is just in the demo data, not the main module but we will fix nonetheless

**Comment by gdgellatly** [comment]
Duplicate anyway of #40 for v12

**Comment by pedrobaeza** [comment]
Fixed at 7da663505369968f3617fd2989333308969d750a
