### ISSUE TITLE
[12.0] Ticket creation button from portal

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/helpdesk#183]
Hello, 

I checked on both 12.0 and 13.0 runbots but the "create new ticket" button is not present in portal. 

Any idea what setup is necessary to display it?

![image](https://user-images.githubusercontent.com/55489873/100603194-08c65200-3305-11eb-9eb7-85dc0666ce68.png)

**Comment by bodedra** [comment]
@francesco-ooops Currently this is only visible for Portal users.

![Screenshot from 2020-11-30 08-48-57](https://user-images.githubusercontent.com/14229503/100631572-18d03880-32e9-11eb-9016-a27d40885606.png)

![Screenshot from 2020-11-30 08-48-59](https://user-images.githubusercontent.com/14229503/100631585-1d94ec80-32e9-11eb-9f2a-1abc4126ed32.png)

I have proposed PR https://github.com/OCA/helpdesk/pull/184 to create a new ticket for all users internal & portal.

**Comment by francesco-ooops** [comment]
Thanks a lot for your help!
