### ISSUE TITLE
[RFC] ticket tree view decoration depending on stage

### ISSUE THREAD

**Issue by dalonsod** [OCA/helpdesk#191]
Hello,

I'm thinking about making a new addon for a ticket tree view improvement: changing ticket record decoration depending on the stage (e.g. if a ticket is closed or unattended). `helpdesk_mgmt_timesheet` already does it, with a certain condition (https://github.com/OCA/helpdesk/blob/12.0/helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml#L26).

My questions are: 
- Should this addition be a new addon, or an improvement for `helpdesk_mgmt`?
- What is the best approach in order to prevent problems with `helpdesk_mgmt_timesheet`?

Thanks in advance!

cc @DarioLodeiros

**Comment by gdgellatly** [comment]
Well, this is always a can of worms.

Firstly compatibility, I don't necessarily agree with what timesheet does, as it is a bit unintuitive. Remaining hours less than zero is not a dangerous situation for most people. Certainly no more dangerous than a missed SLA, an unassigned ticket, a high priority ticket for example.

But I'm also not sure of the value of your proposal, closed and unattended are both already view filters - so these colours would only communicate information where filters aren't used. To provide consistency with other modules I'd say

Blue - unassigned (as a proxy for new, inline with Sale behaviour for Quotes)
Muted - closed.

Unattended for me is a bit workflow dependent, it could be either blue or muted or something else. If we accept that we need to know two conditions at once you could use say italics for unattended.

That said I would propose it in the main module and avoid conflict simply by not using the danger decoration.

**Comment by dalonsod** [comment]
Thanks for the answer @gdgellatly , I'll take a look at your proposal. Closing this.
