### ISSUE TITLE
New Module: Website Helpdesk

### ISSUE THREAD

**Issue by agent-z28** [OCA/helpdesk#20]
We already realized with our Partner BizzAppDev a module to enable to user to see his tickets in the customer portal on the website.
Is anybody already working on this? If not we will create a PR

**Comment by pedrobaeza** [comment]
Portal is (or will be) integrated in main module.

**Comment by agent-z28** [comment]
Portal as portal user?.
But the other case that you want the website portal?

**Comment by pedrobaeza** [comment]
Portal since v11 is frontend views (like website).

**Comment by agent-z28** [comment]
Okay then i close and throw the module in the bin :(
