### ISSUE TITLE
Recipients in CC of email are not attached to tickets 

### ISSUE THREAD

**Issue by Dani0s** [OCA/helpdesk#207]
Hello,

In an installation with OdooCO v12 (commit https://github.com/odoo/odoo/commit/2427b3829c8fe90570e42f9dd8db02e6db5bd527) with the next modules installed:
- helpdesk_mgmt 12.0.1.22.2
- helpdesk_mgmt_project 12.0.1.1.0
- helpdesk_mgmt_timesheet 12.0.1.1.1

I don't know if the next issue is a failure or maybe a new feature for the helpdesk_mgmt module.

When a customer creates a ticket from its email client with CC recipients in its email the CC recipients aren't attached to the ticket as followers.

And when the customer answers a ticket with its email client adding new CC recipients, the same thing happens, the new CC recipients aren't attached to the ticket as followers.

**Comment by pedrobaeza** [comment]
That only happens if the CC are already created as partner. That's something standard, not of this module itself. You can get them with `mail_tracking` module.

**Comment by Dani0s** [comment]
> That only happens if the CC are already created as partner. That's something standard, not of this module itself. You can get them with `mail_tracking` module.

@pedrobaeza excuse me, but I installed the module `mail_tacking`, and when a customer creates a ticket from its email client with CC recipients in its email, where these recipients exist as contacts previously, these contacts aren't attached as followers to the ticket.

There is no way to create contacts with the CC recipients, at the same time is created contact with the partner?

**Comment by pedrobaeza** [comment]
No, auto-creation of contacts is not covered by core or any OCA module I know, and I think it's dangerous. CC mails (being known or not) should be proposed to be added as recipients the next time you reply in the ticket, isn't it?

**Comment by Dani0s** [comment]
> No, auto-creation of contacts is not covered by core or any OCA module I know, and I think it's dangerous.

Excuse me, but when a new customer sends an email to our email in `helpdesk_mgmt`, if the email of the customer isn't existing before, the module `helpdesk_mgmt`creates a new contact with the customer email.

I think this behavior is needed and desired, including CC, if it doesn't happen like that, the communication with all the people involucred in the ticket is broken  :pensive:.

> CC mails (being known or not) should be proposed to be added as recipients the next time you reply in the ticket, isn't it?

No, the CC recipes aren't proposed to be added :pensive:.

I attach a screenshot where it should have three proposed emails, but only one appears, and it is the partner email (none from CC recipes)

![image](https://user-images.githubusercontent.com/45687399/108830118-4c112380-75c9-11eb-925f-191d39d06e1c.png)
