### ISSUE TITLE
FUN ISSUE: I prefere this icon

### ISSUE THREAD

**Issue by agent-z28** [OCA/helpdesk#21]
![icon](https://user-images.githubusercontent.com/7473428/59267841-8b5bdd00-8c4b-11e9-9d5f-8b69fc210ded.png)

maybe at least this can be adapted from our module ://:S

**Comment by pedrobaeza** [comment]
Take care with #MeToo movement...

**Comment by agent-z28** [comment]
it's a 3rd gender picture^^

**Comment by nacho-domatix** [comment]
Really? :palmface

**Comment by emagdalenaC2i** [comment]
I think this issue should be closed (there are some reasons to do that) and move this to a whatsapp group (which I can mute if I'm invited)

**Comment by agent-z28** [comment]
We have no WhatsApp. And we melted two whole projects, i think theres Also some space for fun!?
