### ISSUE TITLE
"Assigned Ticket" email being sent to the customer

### ISSUE THREAD

**Issue by lukejcn** [OCA/helpdesk#215]
Each new ticket is created from an email, but when the ticket is assigned to a user, the customer that sends the email is getting a notification for the assignment too. How can I only send these notifications to the users and not all the followers?

**Comment by lukejcn** [comment]
Apologies, I can see there's already a pull request for a solution to this:
https://github.com/OCA/helpdesk/pull/125

**Comment by gdgellatly** [comment]
Closing this as resolved in 14.0 and will be forwarded to 15.0.
