### ISSUE TITLE
A new ticket is created when an internal user responds (from their email) to an email corresponding to a previous ticket

### ISSUE THREAD

**Issue by alagarda96** [OCA/helpdesk#230]
In the helpdesk module, having the generation of tickets via email activated, occasionally, when responding to emails already linked to a ticket, a new ticket is generated. What could be happening? The subject is not modified, nor the recipients.

**Comment by gdgellatly** [comment]
@alagarda96 If I had to guess, Office365 user and Outlook mobile client is most likely. It strips the identifying headers. But really any mail server/client that strips X-Headers will do the same.
