### ISSUE TITLE
Ticket Portal Page (/my/tickets) not translatable

### ISSUE THREAD

**Issue by llabusch93** [OCA/helpdesk#238]
The portal ticket list page (/my/tickets) is not translated (table headers, but also the content like the stages), despite the fact that the terms are translated in the database (ir.translation). Other portal pages don't have this issue, like the ticket details page (/my/ticket/<ID>). Could also confirm this on OCA runbot.

Any idea on this?

**Comment by marcos-mendez** [comment]
You have to choose user language for this to work, already check in OCA and locally and is translatable.

I Suggest closing this issue

**Comment by llabusch93** [comment]
Hello @marcos-mendez 

I can not confirm this. It does not work locally, neither on the OCA runbot. As I wrote, all other helpdesk portal pages are in German, only the list (/my/tickets) stays untranslated all the time.
So I have the user language set, otherwise the other pages would not be in German, right?

So if it does really work for you, what I doubt, I would be interested in a demo video or screenshot.

**Comment by llabusch93** [comment]
Still have the problem on my customers production, but can't reproduce this on runbot anymore. I assume that it might have to do with the Odoo 12.0 version I use. I will upgrade Odoo an report back here if that solved the issue.
