### ISSUE TITLE
I installed de_helpdesk but it doesn't appear in my module panel, I can't use it.

### ISSUE THREAD

**Issue by eivanprietop** [OCA/helpdesk#245]
post-install the de_helpdesk, the application does not appear in the application panel, post-install there was no error.

The application appears installed correctly, but I cannot use it, the module does not appear in the panel.
![helpdesk parte1](https://user-images.githubusercontent.com/11510017/126049347-82898d40-f986-45dc-b4ed-fd3cc2c6c3c0.png)
![helpdesk parte2](https://user-images.githubusercontent.com/11510017/126049349-a9b7c64f-4ed6-4150-9537-892155c7c87c.png)

**Comment by pedrobaeza** [comment]
That module doesn't belong here.

**Comment by eivanprietop** [comment]
> That module doesn't belong here.

What do you mean, the help desk module is installed in this panel as help desk, I have already installed it on other occasions.

**Comment by pedrobaeza** [comment]
There's no module de_helpdesk in this repository.
