### ISSUE TITLE
Why is task_id computed in heldesk_mgmt_project and always False?

### ISSUE THREAD

**Issue by gdgellatly** [OCA/helpdesk#253]
https://github.com/OCA/helpdesk/blob/8a21a3cf3b0b9f1c481c428dca8ef93cd367f2f3/helpdesk_mgmt_project/models/helpdesk_ticket.py#L11

Hi,

I'm struggling to understand this. This compute field makes it impossible to create a new task in the ticket, which to me would seem the natural workflow, or at the very least a valid one. Client raises issue, assign to a project, and for internal management you create a task. Sure you might link to an existing task but I don't see the case as any less valid. 

Does anyone know why it is like this?
Bonus question, does anyone know how to override this behaviour? I tried `compute=None`, `compute=False` but neither works.

**Comment by dalonsod** [comment]
Hello @gdgellatly ,

if you take a look to v12 code (previous to compute editable fields, then using `onchange` event, https://github.com/OCA/helpdesk/blob/12.0/helpdesk_mgmt_project/models/helpdesk_ticket.py#L18), you'll guess that the desired functionality is only unsetting task value when changing project.

In v13 that code was switched to the new compute editable fields. I've tested it un v13 runbot and works well IMO, even creating a new task during ticket creation. Not tested in v14.

> Bonus question, does anyone know how to override this behaviour? I tried compute=None, compute=False but neither works.

Maybe writing back code to an `onchange` schema should work for you, but I don't really know.

**Comment by pedrobaeza** [comment]
Why is that a problem and why do you want to disable it?

**Comment by gdgellatly** [comment]
@pedrobaeza I could tell you, but you wouldn't believe me. I scarcely believe it myself now I found the real issue.

**Comment by pedrobaeza** [comment]
Ok, no problem. The important thing is that you get to it.
