### ISSUE TITLE
There is no checkbox to activate fiscal annual periods odoo 13

### ISSUE THREAD

**Issue by eivanprietop** [OCA/helpdesk#255]
I have accounting configured for Mexico in odoo 13, when Accessing Accounting> Configuration> Periods> Fiscal years, it appears like this:

![Captura de pantalla de 2021-08-23 12-40-26](https://user-images.githubusercontent.com/11510017/130494173-3ab092d7-4222-410e-ba4b-8bb7ed5350b2.png)

I don't understand why, could you please help me

**Comment by pedrobaeza** [comment]
This is not related to this repository nor an issue, but question, so closing.

**Comment by eivanprietop** [comment]
I understand, thanks for answering.
