### ISSUE TITLE
[RFC] Ticket Portal Refactoring

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/helpdesk#257]
Hi guys, I'm refactoring the ticket portal and would like to share a preview with you. I understand that this style is more standardized with the other portals.

![image](https://user-images.githubusercontent.com/3595132/131002614-4d59d562-5b8d-48ce-8410-b54d3006d4c0.png)

![image](https://user-images.githubusercontent.com/3595132/131004418-9aec164b-fe4a-4b0e-a22a-09f3e1a521c0.png)

Also, I removed the create new ticket button and changed it so that the tickets section is available even if there is no ticket registered.

![image](https://user-images.githubusercontent.com/3595132/131003453-07ad0ba8-26ec-4102-bb40-ebd8aecfb453.png)

Also, I removed the create new ticket button and changed it so that the tickets section is available even if there is no ticket registered. Therefore, the button to create a new ticket was only in the ticket tree.

I would like feedback from the community.

**Comment by marcelsavegnago** [comment]
How is it today

![image](https://user-images.githubusercontent.com/3595132/131004613-ed6d48a7-df0d-440c-b772-230f151c0e6b.png)

![image](https://user-images.githubusercontent.com/3595132/131004641-31928e26-363f-4845-b3ea-1f3632c15d29.png)

![image](https://user-images.githubusercontent.com/3595132/131004684-f0dd74e4-ba82-49f2-b493-9948c6532a5e.png)

**Comment by gdgellatly** [comment]
@marcelsavegnago The ticket number is kind of needed too. My clients who use it always ask for this

**Comment by marcelsavegnago** [comment]
@gdgellatly Great... my clients need it too. I'll add.

Thanks for the feedback.

**Comment by marcelsavegnago** [comment]
@gdgellatly What do you think about simplifying the ticket list?

![image](https://user-images.githubusercontent.com/3595132/131552122-c28700b3-05cc-485a-b2e7-b7813c93d2f4.png)

**Comment by gdgellatly** [comment]
@marcelsavegnago Many years ago I stopped for a beer at the pinguim bar by the opera house. In fact spent a few days there.

For me I think we need dates, probably create and close and maybe last_stage_change. For my clients with many tickets, their clients basically try to find them like they find emails - especially if tickets are created by email.

I don't know if you did as part of this but we will need to improve the search options too at some point. I think also we will need a either a default groupby of stage, or a default filter of 'Open Tickets'.

Pill boxes look good, I just wonder about color coding them but don't care.

**Comment by marcelsavegnago** [comment]
@gdgellatly Very cool .. Did you stay in Ribeirão Preto? If I told you that I practically never went to the Pinguim Bar near the opera, would you believe it? :D

About date columns I understand and will add again.

About stage grouping I was thinking about this yesterday. I'll work on that and also on the open tickets filter.

About the pill boxes I thought about applying colors but I was in doubt. We can consider the stage's parameters to determine different colors accordingly (unattended, closed) or create a field in the stage to define which color to use. What do you think?

**Comment by marcelsavegnago** [comment]
@gdgellatly Date type fields were added again and partner_id.name and category_id fields removed.

![image](https://user-images.githubusercontent.com/3595132/131710449-4e63ebce-e972-4785-a026-a2cc931df8f4.png)

**Comment by marcelsavegnago** [comment]
@gdgellatly Originally the filter is based on steps, do you think it's worth keeping or would it be better to look like the image below?

- All,
- Assigned
- Unassigned
- Open
- Closed

![image](https://user-images.githubusercontent.com/3595132/131716466-df4cfab6-a523-43cb-a398-99cc10c4b8ea.png)

**Comment by gdgellatly** [comment]
Hi @marcelsavegnago 

I spent some days there, maybe 4. Was a business/study trip. I remember arriving on a Sunday morning and that bar was the only place open but we got the manager to open up the opera place for us as well.

For me, from a client usability perspective what am I interested in? Why am I here on this portal?

I'm probably not interested in Assigned Status that is kind of internal. I either want to see progress or update progress, usually on a specific ticket so the option for assignation is meaningless for me.

Open / Closed would be all I'd want. The others I wouldn't care about. No great harm in keeping them, but I can see situations where people won't want their clients to have those options (e.g. unassigned looks like I'm doing nothing) but also they could be confusing, e.g. assigned/unassigned must also filter out done as why would anyone search for an assigned done ticket.

**Comment by marcelsavegnago** [comment]
> Hi @marcelsavegnago
> 
> I spent some days there, maybe 4. Was a business/study trip. I remember arriving on a Sunday morning and that bar was the only place open but we got the manager to open up the opera place for us as well.

Cool. The Pinguim bar is well known and the beer is very cold :)

> For me, from a client usability perspective what am I interested in? Why am I here on this portal?

Yes I agree.

> I'm probably not interested in Assigned Status that is kind of internal. I either want to see progress or update progress, usually on a specific ticket so the option for assignation is meaningless for me.

Okay.. I've already removed it from PR

> Open / Closed would be all I'd want. The others I wouldn't care about. No great harm in keeping them, but I can see situations where people won't want their clients to have those options (e.g. unassigned looks like I'm doing nothing) but also they could be confusing, e.g. assigned/unassigned must also filter out done as why would anyone search for an assigned done ticket.

I simplified it and added grouping by stage. If you can check the PR I would appreciate it.
https://github.com/OCA/helpdesk/pull/258

**Comment by marcos-mendez** [comment]
> Hi guys, I'm refactoring the ticket portal and would like to share a preview with you. I understand that this style is more standardized with the other portals.
> 
> ![image](https://user-images.githubusercontent.com/3595132/131002614-4d59d562-5b8d-48ce-8410-b54d3006d4c0.png)
> 
> ![image](https://user-images.githubusercontent.com/3595132/131004418-9aec164b-fe4a-4b0e-a22a-09f3e1a521c0.png)
> 
> Also, I removed the create new ticket button and changed it so that the tickets section is available even if there is no ticket registered.
> 
> ![image](https://user-images.githubusercontent.com/3595132/131003453-07ad0ba8-26ec-4102-bb40-ebd8aecfb453.png)
> 
> Also, I removed the create new ticket button and changed it so that the tickets section is available even if there is no ticket registered. Therefore, the button to create a new ticket was only in the ticket tree.
> 
> I would like feedback from the community.

LGTM Loved it

**Comment by marcos-mendez** [comment]
> Hi @marcelsavegnago
> 
> I spent some days there, maybe 4. Was a business/study trip. I remember arriving on a Sunday morning and that bar was the only place open but we got the manager to open up the opera place for us as well.
> 
> For me, from a client usability perspective what am I interested in? Why am I here on this portal?
> 
> I'm probably not interested in Assigned Status that is kind of internal. I either want to see progress or update progress, usually on a specific ticket so the option for assignation is meaningless for me.
> 
> Open / Closed would be all I'd want. The others I wouldn't care about. No great harm in keeping them, but I can see situations where people won't want their clients to have those options (e.g. unassigned looks like I'm doing nothing) but also they could be confusing, e.g. assigned/unassigned must also filter out done as why would anyone search for an assigned done ticket.

I don't agree with you, certain tipe of helpdesk we need to know who it is assigned to so user can provide feedback or answer to the matter. For example Hospital maintenance if backup is needed or supply for parts. Maybe so urgent backup is filtered for the user.

**Comment by gdgellatly** [comment]
@marcos-mendez but you do agree. If it is only for a certain type of helpdesk, then it shouldn't be in the general module. 

But in any case, you have completely misread or do not use the module. We are talking of Assigned Status, not of who it is assigned to. That information is already in the ticket and part of the messaging.

**Comment by marcos-mendez** [comment]
A ok ok, yes yes in this case yes. I didnt understand. In that case i can
try to use a parallel module in helpdesk. ok. LQTM

Sorry buddy 🍺🍺

Em qui., 4 de nov. de 2021 às 22:06, Graeme Gellatly <
***@***.***> escreveu:

**Comment by ugoviti** [comment]
> Hi guys, I'm refactoring the ticket portal and would like to share a preview with you. I understand that this style is more standardized with the other portals.

Hi @marcelsavegnago, I like very much your refactoring. In my opinion It's a big enhancement and a must to have, over the official customer portal of OCA-helpdesk.

Do you have worked in a version for the odoo 15 release?

Keep up the good work.

Kind regards

**Comment by marcelsavegnago** [comment]
@ugoviti  Yes I plan to work on it for version 14.0 and 15.0 soon.
