### ISSUE TITLE
Error when open ticket from Kanban view

### ISSUE THREAD

**Issue by FaTaToo** [OCA/helpdesk#266]
**Impacted versions:** 12.0

**Steps to reproduce:**
- This bug is happen randomly when I open any ticket from kanban view.

**Current behavior:**
- This bug is happen randomly
- Form view of ticket was openned but still have search view area and name of the ticket is not the same with the name on control panel.
URL still reference to kanban view: /web?debug=assets#action=465&active_id=1&model=helpdesk.ticket&view_type=kanban&menu_id=289.

**Expected behavior:**
- When form view of ticket was opening, search view should be hidden and name of ticket should be the same with the one on control panel.
- URL should reference to form view: /web?debug=assets#id=81470&action=465&active_id=1&model=helpdesk.ticket&view_type=form&menu_id=289

**Video/Screenshot link (optional):** https://prntscr.com/1rkhhat

**Comment by dalonsod** [comment]
Hello @FaTaToo this issue appears to belong to Enterprise helpdesk addon, not OCA one.

**Comment by pedrobaeza** [comment]
Anyways, without clear steps to reproduce the problem, nothing to do. I'll reopen if we have them.

**Comment by FaTaToo** [comment]
thank you @dalonsod  and @pedrobaeza , I am developer for a company and we are using Enterprise module. Cause I don't know Subscription Code, so I cannot ask on odoo.com/help and that is why I post here. The bug happens randomly when I click ticket from kanban view so it's hard to tell exactly step to reproduce, just click on ticket and the bug happen. Anyway, I just post here with the hope that some experience developers can guess some reasons why the bug happen, why the URL not change after click on ticket.
