### ISSUE TITLE
Problem importing products xlsx file

### ISSUE THREAD

**Issue by eivanprietop** [OCA/helpdesk#273]
When importing xlsx file of products it sends me the following error:

An unknown problem occurred during import (possibly lost connection, data limit exceeded, or memory limits exceeded). Please try again if the problem is temporary. If the problem persists, try splitting the file instead of importing it all at once.

The file has 1000 lines, I already tried 500 lines, it sent the same error.

I already modified in the configuration file:

limit_time_cpu = 60 to 6000
![Captura de pantalla de 2021-10-12 10-55-04](https://user-images.githubusercontent.com/11510017/136989623-415ba25f-8967-433a-97d7-aec0e4903a51.png)

limit_time_real = 120 to 6000

and it sends me the same error.

Can you help me, please.

**Comment by pedrobaeza** [comment]
Your issue has nothing to do with the modules of this repository, so closing.
