### ISSUE TITLE
module icon image does not appear in main panel

### ISSUE THREAD

**Issue by eivanprietop** [OCA/helpdesk#274]
Install the om_hr_payroll module and it works correctly, but the module icon does not appear in the main panel.

I already updated the module and even so the icon does not appear, I already uninstalled it and reinstalled it and the icon still does not appear.

can you help me please.
![Captura de pantalla de 2021-10-12 10-58-11](https://user-images.githubusercontent.com/11510017/136991319-89a4719d-1be1-4322-95d3-b2aa2a05fad5.png)

**Comment by pedrobaeza** [comment]
Such module is not of this repository, so closing.
