### ISSUE TITLE
Adding followers in message_new() and message_update()

### ISSUE THREAD

**Issue by santa-asmane** [OCA/helpdesk#282]
## Module
helpdesk_mgmt: https://github.com/OCA/helpdesk/blob/14.0/helpdesk_mgmt/models/helpdesk_ticket.py
Lines 215 and 231

You should probably use "p.id" instead of "p", because message_subscribe() needs a list of partner IDs, not a list of partner browseable records, but _mail_find_partner_from_emails() returns browseable records.

This leads to errors, while processing incoming e-mails, like: "psycopg2.ProgrammingError: can't adapt type 'res.partner'"
This, in turn, leads to odd behaviours like not registering a reply message or not calling message_post() with the source message on the created ticket.

**Comment by dalonsod** [comment]
Hello @santa-asmane thanks for the feedback. This should be fixed by #280 , could you take a look?
