### ISSUE TITLE
[14.0] helpdesk_mgmt 14.0.1.1.1 depends on openupgradelib (but not in manifest)

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#288]
I updated the module and an issue about missing openupgradelib was raised while migration.
Yet, openupgradelib is not mentionned in dependencies.

**Comment by pedrobaeza** [comment]
This is an old debate. You don't need `openupgradelib` for the module. Just to upgrade. No upgrade, no lib requirement, but such lib is a must in any deployment, as it's widely used. You should consider it a deployment requirement if you plan to do rolling releases (which I recommend) against frozen ones.

**Comment by luffah** [comment]
I understand. 

Would it be a bad idea to add it in manifest with a key ignored by Odoo ? 
```python
    "migrations_external_dependencies": {
        'python': ['openupgradelib']
    },
```

**Comment by pedrobaeza** [comment]
Do you mean for information purposes? I don't see it very valuable, as that's the only library that is going to appear.

**Comment by luffah** [comment]
Yes, mostly for information purposes but it could be used by some script.  As example, Drupal have this kind of field (migration_dependencies) in module description. Here was the theory.
If nobody use any other lib in real life for migration (most migrations i've seen doesn't  even use openupgradelib) it would be not very valuable except for warning about openupgradelib requirement (and maybe version requirement).
Yet (still theory), we can imagine future use of IA processing lib for migrations.

Anyway the issue is not specific to the module repository.
