### ISSUE TITLE
Broken style on portal ticket  pages

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#289]
Some styling errors are presents.
Sorry for the bug label, there is a mix of buggy style and improvement ideas.

### Client customization recommendations
To correct on client customization it requires to inherit or override the following templates.
Given the style is somehow broken, i recommend to override the templates to avoid conflict on module update.

### Templates that could be nicer
**helpdesk_mgmt.portal_my_home**

- the 'New ticket' button could be more elegant, by making the button floating aside the "Tickets" entry, instead of taking a whole row. 
Example:
```xml
<div style="position:relative" >
            <t t-call="portal.portal_docs_entry">…</t>
            <form style="position:absolute; top:0; right:-2ch" method="POST" t-attf-action="/new/ticket">…+…</form>
</div>
```

### Templates that appear broken

**helpdesk_mgmt.portal_helpdesk_ticket_page**

- class 'pull-right' and 'pull-left' are used without using 'clearfix' on parent div
- ticket name is more likely to be an 'h1' than an 'h4'
- the div containing ticket name shall have ```class="col"``` instead of ```class="col-md-6"``` in order to push the ticket closing button on right

**helpdesk_mgmt.portal_helpdesk_ticket_page**

- When hovering with cursor an item in the ticket list it have an effect suggesting the item is clickable. But only the title is clickable. As a workaround the row can be defined as following ```<tr t-attf-onclick="window.location='/my/ticket/#{ticket.id}'" style="cursor:pointer">``` (by some chance, it doesn't affect accessibility while improving UX)

**Comment by marcelsavegnago** [comment]
@luffah Just for the sake of knowledge, I recently started a PR to refactor the ticket view in the portal. If you are interested and want to check it out.
https://github.com/OCA/helpdesk/pull/258
