### ISSUE TITLE
[14.0] helpdesk_mgmt : security and standards 

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#291]
Given our context is for a portal user (frontend), if we compare tickets with projects :
   - it looks like the code and views can be simplified using portal.mixin 
   - project use `ir.rule` for portal users,   helpdesk ticket have instead  ` domain = [("partner_id", "child_of", partner.id)] ` in controller could (should?) be an `ir.rule` too, in order to allow advanced ticket sharing by modifying `ir.rule' (and not rewriting the whole controller)

**Comment by pedrobaeza** [comment]
I think this has been tackled in #285, but I have asked for a split of the improvements.

**Comment by pedrobaeza** [comment]
Fixed in eb348d91a6b11bc90955ec4d899e43dab43b1286
