### ISSUE TITLE
[15.0] Can't test helpdesk_mgmt on runbot

### ISSUE THREAD

**Issue by flachica** [OCA/helpdesk#294]
I review logs and something was wrong. I think that has failed because [0a problem](https://runbot2-2.odoo-community.org/runbot/static/build/3529161-15-0-2317ae/logs/job_10_test_base.txt) with DevOpvs. I think that can't find the virtualenvironment

**Comment by sbidoul** [comment]
Hello,

runbot does not work for 15.0 and is in phase-out for other branches.

Look for the runboat links instead:

![image](https://user-images.githubusercontent.com/692075/151783025-a0b27c60-872e-458e-8874-5292c898d92e.png)
