### ISSUE TITLE
[12.0] E-mails beeing hardcoded sent on ticket creation and assignment to current user

### ISSUE THREAD

**Issue by brenoalef** [OCA/helpdesk#295]
## Module
helpdesk_mgmt

## Describe the bug
Even when there is no mail template defined for New stage, tickets created by mail send an e-mail notifying the creation.
Also, when a user assigns a ticket to self an e-mail is being sent notifying the user of the assignment. 
I think it's caused by the methods added to helpdesk_ticket.py in https://github.com/OCA/helpdesk/commit/98e5ef7f4a2e074283da3674654f662a28f02eed as they use a predefined template and are being used only in branch 12.0.

## To Reproduce
**Affected versions**:
12.0

For mail being sent on creation:
With an Incoming Mail configuration to create Helpdesk Tickets.
1. Make sure there is no mail template defined for New stage
2. Send an e-mail to address for ticket creation
3. See that the partner receives an e-mail notifying the creation of the ticket

For mail being sent on assignment:
1. Start editing a ticket
2. Change assigned user to current user
3. Save
4. See that an e-mail is sent to current user notifying the change as if it was done by someone else

**Expected behavior**
For mail being sent on creation:
User should only receive an e-mail if there was a configured template.

For mail sent on assignment:
User should only be notified if someone else had assigned a ticket to them.

**Comment by pedrobaeza** [comment]
The first point was solved by me in upper versions, and I have cherry-picked it in v12 in 8ffd5dccda40e9534b7142099c7878b105b86761

Please create another issue for the other.
