### ISSUE TITLE
[12.0] Ticket Creation e-mail beeing sent hardcoded with default template

### ISSUE THREAD

**Issue by brenoalef** [OCA/helpdesk#296]
This was first reported alongside another issue in  #295 

## Module
helpdesk_mgmt

## Describe the bug
Even when there is no mail template defined for New stage, tickets created by mail send an e-mail notifying the creation to the partner.
This occurs because `helpdesk_mgmt.created_ticket_template` is being hardcoded used as template to send e-mails on ticket creation. That part of the code is not present in upper versions.

## To Reproduce
**Affected versions**:
12.0

With an Incoming Mail configuration to create Helpdesk Tickets.
1. Make sure there is no mail template defined for New stage in Configuration  
2. Send an e-mail to address for ticket creation
3. See that the partner receives an e-mail notifying the creation of the ticket

**Expected behavior**
User should only receive an e-mail if there's a template defined for the stage and, in that case, it should use the configured one.
When there's no configured template, the e-mail should not be sent.

**Comment by HekkiMelody** [comment]
I'm not necessarily against this change, but it should be noted that the difference between having the email set at the stage level and this one is that as it currently exists, the email is sent on ticket creation. With your suggestion, if you were to create a ticket directly at a different stage, the email would not be sent.

Maybe a configuration setting would be better?

**Comment by brenoalef** [comment]
There is currently a configuration for mail model by stage. If a ticket is created, in any stage, an e-mail is sent using the configured template. 
As it is now, even if the stage has no configured template, the "ticket created" e-mail is beeing sent. This results in two e-mails being sent if a template is defined for stage New, for example. I've tested creating a ticket at Done stage, and the result was the configured template beeing sent first and after that the hardcoded e-mail saying a ticket was created.
Creating a new configuration would be a solution, but I believe removing this part of the code in 12.0 is simpler and solves the issue.

**Comment by HekkiMelody** [comment]
I don't disagree that the way the module currently behaves is problematic, I'm just pointing out that's it's not an entirely undesirable behaviour and straight-up removing it may not be the best solution.

Such use-case for one of my installations of helpdesk is that whenever a ticket is created (and it's not already on a "closed" stage on creation), a "ticket has been created" email should be sent to the customer. However, this should only happen on creation. If I were to set that "ticket has been created" email template on every single not-closed stage, I'd keep sending the "ticket has been created" email every time I advanced the ticket to a new stage, which is not what I want.

That also means that, yes, if an email is already configured for a certain stage, then two emails should be sent.

I think having a configuration setting where you can change the hardcoded email template would be best. That way, you can also leave that empty, and no hardcoded email is sent on creation. It'd make the module more flexible and make everybody happy, no? Alternatively, splitting this functionality into its own tiny module could also be a solution.

Maybe a maintainer can chime in with a cleaner solution or advise on whether certain use-cases are too niche and should not be included in the base module in the first place.

**Comment by pedrobaeza** [comment]
The way to get the "Ticket is created" mail on creation should be to assign a template to the initial stage where the ticket is created (usually, "New" or similar), so I agree on removing this hardcoded one.

**Comment by HekkiMelody** [comment]
I've made the PR #298

**Comment by homeland3d** [comment]
In version 14.0 not send new ticket notification. When ticket is recieved trough email the odoo not notify the creation.
Can anyone solve this? or have some workaround to do this?
