### ISSUE TITLE
Any chance to switch license of the base module to LGPL-3?

### ISSUE THREAD

**Issue by mjrk** [OCA/helpdesk#297]
I have a couple of feature requests for helpdesk extensions and I would like to implement them as LGPL-3. LGPL-3 is an requirement, because there will be a client specific frontend theme [EDIT: and few fields to incorporate from a proprietary addon. Unfortunately, license wise, it is not possible to combine proprietary Odoo addons with AGPL.]

Therefore, I would like to ask the maintainers if they consider to change the license of the base module helpdesk_mgmt to LGPL-3. Or rather if anytime in the future such a change might be considered.

The biggest helpdesk extending LGPL-3 addon would be for customer returns. Customers could file tickets of special categories with their reason of the return (and refund). 

This is just a non-binding question. If no such change will ever be considered, we know how to proceed.

**Comment by pedrobaeza** [comment]
The license is AGPL specifically for avoiding such extensions like managing returns to be private. I would recommend a `helpdesk_mgmt_rma` bridging with `rma` OCA modules family for that. But all in open.

Theming the portal - understood as giving other aspect - is something that doesn't require to depend on the helpdesk modules, so it's not preventing at all such extension parts, that are logical to be kept as private/custom.

**Comment by mjrk** [comment]
@pedrobaeza Thanks a lot for your response. 

I understand the reasoning. However, the theming requires templates and fields of the helpdesk extension and therefore requires to depend on it ... . Also, the final theming ([EDIT] it's about commercial delivery and payment plantform integrations) needs to combine another addon (non-free) from a different source. 
The planned helpdesk extension offers the base frontend functionality. Thus, it cannot be AGPL, unfortunately. (Note, the scope of this feature is different to the OCA rma module.)

If I understand you right, no switch to LGPL-3 will ever be considered. In this case it will have exactly the opposite effect because I need to write a proprietary module based on the Odoo enterprise helpdesk. At least, according to my understanding we have no choice here. We'd rather not, as it makes the setup of testing sites we run without Odoo Enterprise more difficult, or half-baked. In the current live app, the enterprise helpdesk is in use and we try to evaluate if we can switch to an OCA based solution.

Don't hesitate to write your considerations. If no-LGPL is final, feel free to close this issue. I any case, thanks for your efforts!

**Comment by pedrobaeza** [comment]
I'm only one of the contributor (and not very big) of these modules. There are more, but from my part, I don't want to lose the viral component of the AGPL and don't get contributions back. If you go to the ~~dark~~ private side, then benefit from those that play with the community rules with no other gain is not fair for me.

Let's see what other contributors think.

**Comment by mjrk** [comment]
@pedrobaeza Thanks a lot for leaving this issue open. 

I liked the "dark" private comment from above and would like to point out, that when you search for AGPL, that there are some people with (IMHO) valid arguments, that call AGPL the Free Open Source license that is as close to proprietary licenses as it gets. This because of dual licensing and also some programmers view, when they experience that they cannot use AGPL code because of license restrictions in their otherwise Open Source stack.

From my side, I work hard to convert all our stack (where applicable) to Free Open Source, see https://github.com/ayudoo/ . These modules are in use and I receive valuable feedback. Unfortunately, there is still a year of free time work for me to do, so that these modules are published on odoo apps, fully automatic tested and integrated in the OCA maintenance stack.

Now, about the helpdesk. I do not ask you to lose anything, and I'm highly willing to contribute - if I could use it. The problem is that helpdesk integrates a lot of parts of odoo and in different projects we need to integrate external (proprietary) payment and delivery solutions. And, there is no other solution but to extend both, helpdesk and these. But we cannot build this on top of AGLP because of license restrictions. (And there are concerns, that we step into license compatibility issues later, so that I'm actually obliged to LGPL until now.) But everything else, that was made reusable, already is Open Source. And more is to follow.

On the other hand, some time and features passed, and after this time I cannot promise anymore that we could publish and quickly switch all features to use OCA helpdesk in the next year. But I'd plan it for Odoo 17. A feature I could provide earlier is ticket merge and a message history extension according to email address (so you don't miss other emails of the customer in question).

**Comment by pedrobaeza** [comment]
I don't doubt that your intentions may be good, but at the end, using AGPL doesn't mean you have to publish things in OCA. Just that the license in derivative works should be kept, and as so, if someone from your release chain wants to put on open such code, the license grants this.

And it's not only because of you, but changing the module to such license will open the doors to other with no such good intentions to develop private stuff on top of the common ground.

Thus, I'm afraid I stay in my position of not changing it.

**Comment by mjrk** [comment]
Thanks for your quick reply. I did not mention a relationship between AGPL and OCA or did not expressed myself well.

If I understand the argument correctly, the only solution is to develop a new LGPL helpdesk solution. (I mean, only this way we can find an Open Source replacement in our situation.) It seems a bit off, but it's not so much code at the end. Keeping this in mind, I might come back here in the next years. I totally respect your decision, contribution and work.

Still, to everybody it affects: is "reinventing the wheel" exactly that, what we need for core modules? I regard helpdesk a core functionality. Wouldn't it be much more valuable to have a common free Open Source solution that combines more and different (free and possibly non-free) solutions, so that it could replace proprietary/enterprise helpdesks for more users with more features?

**Comment by pedrobaeza** [comment]
I still don't understand why that "pieces" can't be AGPL.

**Comment by mjrk** [comment]
If your task is to extend helpdesk.ticket ( https://github.com/OCA/helpdesk/blob/15.0/helpdesk_mgmt/models/helpdesk_ticket.py ) with related models from proprietary apps, you cannot legally do it. 
So you need to use another helpdesk app. But if this helpdesk is proprietary, it makes little sense (if even possible) to make our other helpdesk extensions LGPL.

**Comment by pedrobaeza** [comment]
Do you mean some kind of connectors to other software packages? That's not illegal.

**Comment by mjrk** [comment]
If I understand license compatibility right, I can neither develop an LGPL or proprietary app on top of AGPL (having an AGPL module in the depends-declaration). Also, I cannot create a AGPL app on top of a proprietary module. I cannot combine them, or is there a special license extension that would allow this?

**Comment by pedrobaeza** [comment]
Of course not, but what I say that is not illegal is to do an AGPL connector to such proprietary packages.

**Comment by mjrk** [comment]
I am confused, is the information given here misleading: https://www.odoo.com/blog/odoo-news-5/adapting-our-open-source-license-245

"Odoo projects will be able to use AGPL modules or paid modules under proprietary licenses, but it is not possible to combine both. Combining LGLPv3 modules and proprietary modules is fine however, so we encourage current owners licensing under AGPL to move to LGPLv3 too, in order to avoid complications for end users."

Btw. I *only* knew a more restrictive interpretation of AGPL than the OCA one - where you cannot even have it together in an integrated system like Odoo. And not restricting it only to the depends-declaration. - I know about the discussion to regard integrated systems with extensions similar to an operating system, and have no problem following it. It's was just new.

**Comment by mjrk** [comment]
Maybe the misunderstanding is that the connectors already exists as Odoo apps, they are free to download, but a proprietary license. And, to re-implement them in AGPL app is not an option, they come together with the partner/service, the amount of code for these APIs is huge. Their usage is not my choice, but the clients. We could not convince the providers to switch license to an Open Source model (we did ask though).

**Comment by pedrobaeza** [comment]
I think your misunderstanding is in the word "combine". You can have an Odoo instance with AGPL, LGPL and Propietary modules installed. The only license problem is if a proprietary module DEPENDS on an AGPL. But if they don't depend each other, then no problem.

Please check this OCA post that can be clearer: https://odoo-community.org/blog/news-updates-1/oca-odoo-meeting-on-licenses-21

cc @OCA/board I think this misunderstanding has been promoted by Odoo to discourage AGPL. You should take it into account in your speech.

**Comment by mjrk** [comment]
There was no question about your point, and the OCA view is made clear an various locations, and as I wrote above, I "have no problem following it". The question is, if I can build an AGPL app with depends on a proprietary module. This would be very surprising, as AGPL requires to publish the whole stack to the user - and I cannot publish the OPL-1, even if it's free to download.

**Comment by pedrobaeza** [comment]
No, you can't do that, but it's more reasonable to replace such proprietary part than the whole stack IMO. Anyways, I think we have become to a dead end on our reasonings.
