### ISSUE TITLE
[14.0] helpdesk_mgmt : Error share button in action section

### ISSUE THREAD

**Issue by alodoanhnhan** [OCA/helpdesk#300]
## Module
helpdesk.ticket

## Describe the bug
The share button in the action section is broken, because the helpdesk.ticket model has not inherited the portal.mixin model

1. Add the portal.mixin model to the helpdesk.ticket model
Old: 
`_inherit = ["mail.thread.cc", "mail.activity.mixin"]`

New: 
`_inherit = ["mail.thread.cc", "mail.activity.mixin", "portal.mixin"]`

# Expected behavior
The wizard will be displayed after clicking the share button

**Comment by pedrobaeza** [comment]
Fixed in #323
