### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ktalovmorx** [OCA/helpdesk#315]
while parsing file:/c:/program%20files/odoo15/server/odoo/addons/helpdesk_mgmt/demo/helpdesk_demo.xml:103, somewhere inside <record id="helpdesk_ticket_3" model="helpdesk.ticket"> <field eval="&quot;Document related problems&quot;" name="name"/> <field eval="&quot;Document related problems&quot;" name="description"/> <field eval="&quot;Jaime Bajozano&quot;" name="partner_name"/> <field eval="&quot;contact@tecsas.fr&quot;" name="partner_email"/> <field eval="&quot;1&quot;" name="priority"/> <field eval="[(6,0,[ref('helpdesk_tag_1')])]" name="tag_ids"/> <field name="user_id" ref="base.user_root"/> <field name="stage_id" ref="helpdesk_ticket_stage_cancelled"/> <field name="channel_id" ref="helpdesk_ticket_channel_other"/> <field name="partner_id" ref="base.res_partner_18"/> <field name="team_id" ref="helpdesk_team_1"/> </record>

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue of the module, as it installs correctly in CI environments, so your DB is somehow contaminated. Please start with a fresh install or dig where is the problem in your DB.

**Comment by ktalovmorx** [comment]
Ok, solved
