### ISSUE TITLE
helpdesk_mgmt: Wrong French translation filename

### ISSUE THREAD

**Issue by houzefa-abba** [OCA/helpdesk#374]
Hi,

French localization files Odoo expects are `fr.po`, not `fr_FR.po`

In this repo in the 15.0 branch:
* [helpdesk_mgmt](https://github.com/OCA/helpdesk/tree/15.0/helpdesk_mgmt): `fr_FR.po` - wrong :x: 
* [helpdesk_mgmt_project](https://github.com/OCA/helpdesk/tree/15.0/helpdesk_mgmt_project): `fr.po` - ok :heavy_check_mark: 
* [helpdesk_type](https://github.com/OCA/helpdesk/tree/15.0/helpdesk_type): No French l10n yet

I checked [on runboat](https://runboat.odoo-community.org/webui/builds.html?repo=OCA/helpdesk&target_branch=15.0), activating the French language does fail to load `fr_FR.po`

Solutions, which would you prefer?
1) PR to rename `fr_FR.po` ➔ `fr.po`
2) Create Fr translation [on weblate](https://translation.odoo-community.org/projects/helpdesk-15-0/helpdesk-15-0-helpdesk_mgmt/#translations) & upload into it from the previous one - but this would leave both `fr.po` & `fr_FR.po` next to each other, would be confusing

**Comment by pedrobaeza** [comment]
Please go with 1
