### ISSUE TITLE
Link ticket to sale order

### ISSUE THREAD

**Issue by carlosajh** [OCA/helpdesk#423]
Hello, it's possible link ticket to sales order?

I think that this feature would be great from me and others users. We can track from the point of sale to the end and see a history of incidents assigned to a sale.

Thanks.

**Comment by dalonsod** [comment]
Hello @carlosajh 
There have been at least two helpdesk sale link approaches, you can check at #119 (v13) and #115 (v12). Both modules weren't merged yet, but they could be useful for you.
