### ISSUE TITLE
Incorrect mail address creation when ticket change state 

### ISSUE THREAD

**Issue by pepinho7** [OCA/helpdesk#435]
## Module
helpdesk_mgmt

## Describe the bug
Once the ticket has been created via email from an unregistered user and the stage is changed to 'Done', a contact is created with the wrong email. The **&gt** is added at the end of the email address. For this reason the sending of the mail for the change of stage fails.

## To Reproduce
**Affected versions**:

1.  Go to Settings > Incoming mail servers and set in 'Actions to Perform on Incoming Mails' **Helpdesk ticket** for _Create a New Record_
2. Create a Team with a mail alias that can accept emails from everyone
3. Send from a mail to that alias with an unregistered (external) user
4. Move the automatically created ticket to the 'Done' stage

**Expected behavior**
A mail message should be sent to the mail address that generated the ticket

**Additional context**
Running Odoo 14.0
![resend_mail](https://user-images.githubusercontent.com/54631469/217847819-c1a2be58-f7e9-4efc-bdae-c07e52abaf2e.png)

**Comment by afbenevides** [comment]
Hello, I have same problem.

Before installing module named: Email_Format_Checker (partner_email_check), I had an error message on a new created ticket from outside user by mail: Validation error, Email invalid

After installing Email_Format_Checker, I have exact same error as you,  Validation error, external.user@mail.xx&gt is an invalide email

Did you find the solution to that problem?

**Comment by mathben** [comment]
What is the content of the field partner_email?
When a ticket is create by an external email by email gateway, it's create email like '"Name" <name@company.com>". It supposes to be "name@company.com". When close tickets, I have the same error of you.
Check #491
