### ISSUE TITLE
Add attachment in comment messages of a ticket ?

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#45]
Shall helpdesk_mgmt module integrate attachment button in website comment composer (portal chatter) ?

It can be implemented by disabling current composer in js-widget and adding a custom composer (an easy to maintain qweb template ?).

**Comment by pedrobaeza** [comment]
That should be instead a more generic module that add the possibility of attachments in website comments. But having the option of sending an email as reply for me has been enough.

**Comment by luffah** [comment]
Therefore a module in website/  for website portal comments attachments... Ok.

**Comment by luffah** [comment]
>  But having the option of sending an email as reply for me has been enough.
Do you mean the reply is put in the chatter message automatically ?
Which part of odoo to configure in order to do that ?

**Comment by pedrobaeza** [comment]
Yes, this is done automatically by Odoo having the catchall configured and inheriting from mail.thread (which is the case).

**Comment by luffah** [comment]
I've seen the parameter 'catchall.domain' in system settings.
To use the catchall, do i need to a) set up a true email domain catch-all. OR b) setting a standard mail box named catchall@mydomain can be enough ?

**Comment by pedrobaeza** [comment]
Just have a mailbox and put in on incoming mail servers.

**Comment by luffah** [comment]
Great (yes, it works) ! thank you
