### ISSUE TITLE
Link supplier to ticket

### ISSUE THREAD

**Issue by JoanRibotAE** [OCA/helpdesk#473]
Hello,

In my company we need to link a supplier (from the account module) with a ticket. Is there a module that accomplishes this functionality? I didn't find any.

If not, we would develop it ourselves. Would OCA be interested in us doing a pull request with this module if we develop it?

**Comment by pedrobaeza** [comment]
Honestly, I see that link a bit weird... Anyway, if the module complies with the OCA guidelines and rules [1], why not propose it here? Better here than in other places, and you will benefit from OCA tooling.

[1] https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst
