### ISSUE TITLE
helpdesk_mgmt migrations

### ISSUE THREAD

**Issue by ghost** [OCA/helpdesk#499]
Hello, when migrate odoo from v14 to v15 with helpdesk_mgmt module, openupgradelib cant load file noupdtae_changes.xml.

Here the link to line with a possible bug: https://github.com/OCA/helpdesk/blob/63da14983425f31bd0b2379b1092d1f895746f18/helpdesk_mgmt/migrations/15.0.1.0.0/post-migration.py#L13

I think path should be "migrations/15.0.1.0.0/noupdate_changes.xml"

I changed on my instance to migrate and works fine

**Comment by pedrobaeza** [comment]
Fixed in the commit I have made. Thanks for reporting. You misled me a bit with the typo in the file name at the beginning.
