### ISSUE TITLE
Installation error when activating "Helpdesk Ticket Timesheet" in Odoo 16

### ISSUE THREAD

**Issue by davidir** [OCA/helpdesk#501]
<!-- Provide a general summary of the issue in the Title above.
After installing the other 2 modules in Odoo 16, the "Helpdesk Ticket Timesheet" cannot been installed when you try to activate it showing this error: 

"You try to install module 'helpdesk_mgmt_timesheet' that depends on module 'project_timesheet_time_control'.
But the latter module is not available in your system."

## Module
'helpdesk_mgmt_timesheet'

## Describe the bug
After installing the other 2 modules in Odoo 16, the "Helpdesk Ticket Timesheet" cannot been installed when you try to activate it showing this error: 

"You try to install module 'helpdesk_mgmt_timesheet' that depends on module 'project_timesheet_time_control'.
But the latter module is not available in your system."

## To Reproduce
INSTALL THE OTHER 2 plugins to Odoo 16 and try to install the third

**Expected behavior**
To install correctly helpdesk_mgmt_timesheet

**Additional context**
Seems to have old versions but no with the last 16 from odoo

**Comment by pedrobaeza** [comment]
The module is working on runboat, so it should be in your end. Try on a fresh DB and put more details. Meanwhile, closing.
