### ISSUE TITLE
Template Helpdesk

### ISSUE THREAD

**Issue by castillocon** [OCA/helpdesk#525]
Hello, I would like to ask if there is the possibility in version 16 or future versions, to implement Template in helpdesk as there is in Proyect ? 

Is it possible ?

**Comment by pedrobaeza** [comment]
You can fund any of the contributors to add such feature. Meanwhile, unless someone wants to voluntarily work on that, the feature will be missing.

**Comment by flotho** [comment]
Hi @castillocon , 
thanks for your question.
Maybe you could try to make aPR
