### ISSUE TITLE
How can we set Service Level Agreements (SLA) for a new ticket?

### ISSUE THREAD

**Issue by disenopinnacle** [OCA/helpdesk#533]
Can we add deadline for tickets? and track the time for ticket?

**Comment by dalonsod** [comment]
Hello, please check those functionalities e.g. running runboat for the desired Odoo version.

Time tracking could be achieved with `helpdesk_mgmt_timesheet` addon and SLA support with `helpdesk_mgmt_sla` one, both availables for some but not every Odoo version.

**Comment by flotho** [comment]
please @disenopinnacle this issue could be closed
