### ISSUE TITLE
group error

### ISSUE THREAD

**Issue by Hiregui92** [OCA/helpdesk#538]
https://github.com/OCA/helpdesk/blob/d490e7f2d60016ef609063eea4b3998bc60ab73e/helpdesk_mgmt/views/helpdesk_ticket_views.xml#L190

**Comment by dalonsod** [comment]
Hello @Hiregui92 could you provide more information?

**Comment by Hiregui92** [comment]
> Hello @Hiregui92 could you provide more information?

Yes, that view have a problem in distribution. I things we can chance, we need to remove group.

In this moment branch 16.0
helpdesk_ticket_views.xml 
`<group>
    <notebook>
        <page string="Description" name="description">
            <field name="description" widget="html" />
        </page>
        <page string="Other Information" name="other_info">
            <group>
                <field name="last_stage_update" readonly="1" />
                <field name="assigned_date" readonly="1" />
                <field name="closed_date" readonly="1" />
            </group>
        </page>
    </notebook>
</group>`
![image](https://github.com/OCA/helpdesk/assets/23295975/083f4250-2a70-4b95-aaba-6fc8cdb2a757)


Without group 
```
<notebook>
    <page string="Description" name="description">
        <field name="description" widget="html" />
    </page>
    <page string="Other Information" name="other_info">
        <group>
            <field name="last_stage_update" readonly="1" />
            <field name="assigned_date" readonly="1" />
            <field name="closed_date" readonly="1" />
        </group>
    </page>
</notebook>
```


![image](https://github.com/OCA/helpdesk/assets/23295975/63aba2ec-49a9-4e10-a24b-b36105d39fc7)

**Comment by dalonsod** [comment]
Inspecting at v16 runboat, it seems to work correctly, could you try? Looking at provided snapshot you've got some custom adaptations and/or not merged yet modules, like SLA one, that can break form as you show.

**Comment by flotho** [comment]
looks like you're unsing helpdesk OCA in enterprise setup. Maybe some conflicts occured?
