### ISSUE TITLE
wrong company assignment on ticket creation

### ISSUE THREAD

**Issue by Querens** [OCA/helpdesk#543]
## Module
Helpdesk Management

## Describe the bug
I've created several ticket teams under 3 different companies. For some reason some tickets are assigned to the wrong company. I couldn't track the source of the problem and this looks like a bug.

## To Reproduce
**Affected versions**:
Odoo 16.0-20230629 (Community Edition)

1. Setup 3+ companies
2. Create 6+ ticket teams and assign companies arbitrary
3. Start receiving emails until some of the tickets will be assigned with the wrong company

**Expected behavior**
On creation tickets assigned to the company owning a ticket team 100% of the time

**Additional context**
I've been working with Odoo for 4-5 months already and it doing great so far. I've been seeing tickets assigned wrong for a while now but I haven't paid much attention to it until I realized that I've answered with a wrong company logo and signature a few times. I've tried to research settings and relations of models to track down the problem myself but with no success so far.  I would appreciate any help to track down the source of the problem

**Comment by dalonsod** [comment]
Hello @Querens please check if you've got the latest version of `helpdesk_mgmt` addon, and see #511 that fixes a multicompany bug (not sure if it's the same bug)

**Comment by Jan-Onestein** [comment]
The issue from @Querens is still there and wasn't resolved @dalonsod

Additional info regarding the issue at hand that I found.
note: found on a 16CE build with 8 companies with 2 companies with multiple helpdesk teams.
Tickets are created by setting the option on the incoming mailserver
This is then resulting in a ticket assigned to the right team but created in the wrong company.
The company where the ticket is created, seems to be related to the default company of the user that pulls the mail.
(either odoobot that has by default only the first company or a user with enough rights)

Hope this will help any developer in resolving the issue.
