### ISSUE TITLE
Server date is used for initial value of last_stag_update

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#55]
In ticket list view `web#model=helpdesk.ticket&view_type=list` : I have ~~inconsistency~~
something i did not expect on last stage update value (last update is before creation...) : the default last stage update is the server start time.

Ticket number | Title | Partner Name | Assigned user | Stage | Priority | Created on | Last Stage Update
 -- | -- | -- | -- | -- | -- | -- | --
HT00032 | Rechargement vue |   |   | New |   | 30/07/2019 12:07:14 | 30/07/2019 11:39:04

Solution in `models/helpdesk_ticket.py`, remove parenthesis in Datetime.now()
```python
    last_stage_update = fields.Datetime(
        string='Last Stage Update',
        default=fields.Datetime.now,
    )
```

**Comment by pedrobaeza** [comment]
Yes, indeed. Please open a PR.
