### ISSUE TITLE
res_config.py + res_config_view.xml

### ISSUE THREAD

**Issue by acruzdb** [OCA/helpdesk#6]
### Migration module crm_helpdesk_improvement from v8 to v11

- The person in charge of this task must do it based on the module crm_helpdesk_improvement (https://github.com/factorlibre/helpdesk/tree/8.0-FL_Helpdesk_Improvement).

- The pertinent changes must be made to update the model and the view to v11.

**Comment by pedrobaeza** [comment]
Is this already completed?
