### ISSUE TITLE
v12 "No title" as the title of portal ticket list

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#63]
This ticket apply to version 12.0 of this module.

In portal ticket list view, the ticket list is titled with "No title". 
This the result of calling  "portal.portal_searchbar" without any argument "title".
```xml
        <h3>Tickets
           <t t-call="portal.portal_searchbar"/>
       </h3>
```

I suggest to use the same structure than on Project module:
```xml 
        <t t-set="breadcrumbs_searchbar" t-value="True"/>
        <t t-call="portal.portal_searchbar">
            <t t-set="title">Tickets</t>
        </t>
```
This imply to change the controller `myaccount.py` by disabling line `'no_breadcrumbs': False`.

**Comment by pedrobaeza** [comment]
OK, seems good. Go ahead with the PR

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please., could you close this Issue? It is merged
