### ISSUE TITLE
Error the field allow_timesheet" is not present in the view when i try to upgrade module.

### ISSUE THREAD

**Issue by NicolasGlezGlez** [OCA/helpdesk#637]
## Module
helpdesk_mgmt_timesheet

## Describe the bug
When I try to update the module helpdesk_mgmt_timesheet I get the following error. The ‘allow_timesheet’ field used in attrs ({‘required’: [(‘allow_timesheet’, ‘=’, True)]}) must be present in the view, but it is not found. 

View error context:
{‘file’: ‘/opt/odoo/auto/addons/helpdesk_mgmt_timesheet/views/helpdesk_ticket_view.xml’,
 ‘line’: 1,
 ‘name’: ‘timesheet.helpdesk.ticket.form.view’,
 ‘view’: ir.ui.view(4385,),
 ‘view.model’: ‘helpdesk.ticket’,
 ‘view.parent’: ir.ui.view(3848,),
 ‘xmlid’: ‘timesheet_helpdesk_ticket_view_form’}

Translated with DeepL.com (free version)

## To Reproduce
**Affected versions**: 15.0

Upgrade module.

**Comment by pedrobaeza** [comment]
Remove manually the view before upgrading. It's a glitch on how Odoo checks integrity of the views.
