### ISSUE TITLE
Adding searchbar in portal ticket  list (similarly to Tasks)

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#64]
I intend to add a text input in searchbar in portal ticket  list (similarly to Tasks) , shall it be included in helpdesk_mgmt module.

Which properties shall we include (in oca module) for search with input text ? 
- [x] _all_ 
- [x]  name
- [x]  description
- [ ]  chatter messages _Edit: [pedrobaeza referenced a module](https://github.com/OCA/helpdesk/issues/64#issuecomment-519158639) that do most of the job_
- [x]  assigned user
- [x]  category

**Comment by pedrobaeza** [comment]
Except chatter messages (it's going to be very slow and might require other modules like https://github.com/OCA/server-tools/tree/12.0/base_search_fuzzy), the rest seems OK.

**Comment by rvalyi** [comment]
well, I know people interested in chatter messages search... I don't know, may be an option to enable it?

**Comment by pedrobaeza** [comment]
That should be a separated module if there are extra dependencies

**Comment by pedrobaeza** [comment]
Similar to https://github.com/OCA/social/tree/12.0/base_search_mail_content

**Comment by luffah** [comment]
> Similar to https://github.com/OCA/social/tree/12.0/base_search_mail_content

May the optionnal dependencies be included in code... if the admin installed the module, then searching in the "content" or "all" lookup message too.

**Comment by luffah** [comment]
Given the search bar is include in Projet module only in odoo 12. Shall the change be made for helpdesk in v11 or shall it be only for v12 (to be homogeneous with Project module) ?

_Edit : in fact , i'm not sure if it is present or not in Project module; i found code lines that say it is included_

**Comment by pedrobaeza** [comment]
If it's technically possible in v11, I don't see why we can't include it in that version, although project won't include it till v12.

**Comment by luffah** [comment]
The change is ready for v12 https://github.com/osiell/helpdesk/tree/12.0-add-searchbar-input modulo some pull-requests.
I'm studying the case for v11.
