### ISSUE TITLE
From mail ticket creation, computed partner_id is not always the best choice

### ISSUE THREAD

**Issue by luffah** [OCA/helpdesk#67]
_Minor bug._

When creating a ticket by sending a mail (fetchmail), the partner_id is the first one found with matching mail address.

However it could be nicer to try to match a partner_id which is an helpdesk user if many matching mails are found.

See in code `helpdesk_mgmt / models / helpdesk_ticket.py`,   `def message_new ()`

**Comment by pedrobaeza** [comment]
Uhm, isn't `partner_id` the "customer"? So why matching with a helpdesk user?

**Comment by luffah** [comment]
Oh sorry, I was thinking granting access to portal for a customer create a res.user .
My aim is to provide an interface for the customers (and people inside the company, too) to see how evolve the tickets created (by him/her-self).

**Comment by pedrobaeza** [comment]
But that is done through record rules using followers as granted users are adding the sender as follower on ticket creation.

**Comment by luffah** [comment]
I think there is a second subject in this thread : i don't know if it is the expected behaviour.
* I grant portal access to a partner A. 
* I set up the partner_id of a ticket to partner A. Too, i assign a task to the partner A (in a project).
* The partner A connect to the portal. The partner A see 1 task but no ticket.

Edit : in my test, A was an internal user.

**Comment by pedrobaeza** [comment]
Tasks work also by followers. If you remove partner A from followers in the task, he/she doesn't see the task either.

**Comment by luffah** [comment]
Thank you for your patience.
Maybe the information shall be in present in README.

**Comment by gdgellatly** [comment]
@luffah This is as resolved as it is going to get after 1 year. The behaviour is pretty standard Odoo, however if you feel it needs documentation, please feel free to make a PR.

I think there is also a requirement for an option, potentially at team level or globally to autosubscribe partners to helpdesk tickets, this question comes up quite a bit, there is a duplicate issue #159  for your sub issue so I close this one. I will probably write the change anyway as I want autosubscribe.

Thanks for raising.
