### ISSUE TITLE
[General Question]What is the functionnal roadmap of this repo

### ISSUE THREAD

**Issue by flotho** [OCA/helpdesk#91]
Hi,

First of all I would like to congratulate this initiative that looks amazing.
My question is fairly simple and I hope that I won't be misunderstood.
What is the main difference with project management available in Odoo CE + OCA repo ?

As I'm about to migrate from 10.0 to 12.0 our main instance, as I'm suspecting that great things are about to be achieved here, I would like to have more precision regarding the Roadmap to decide wether I migrate our support activity from project to heldesk .

Thanks for reading and for any answer.

Regards

**Comment by pedrobaeza** [comment]
@rvalyi @dxnacho can you give your opinion?

**Comment by nacho-domatix** [comment]
Hi @flotho, first of all thanks for your comment.

Not sure I really undestand the question, Project Management and Helpdesk provide different  features (as they do in Odoo Enterprise).

Helpdesk main goal is to manage all communication with customers, suppliers or any other users in Odoo, and that link "issues" to sale orders, tasks in projects, invoices.... 

Todo list is to pulish issues from email, satisfaction survey and any other feature you can think of ;) (we've got already more features than Enterprise).

Hope this answer can help you, anyway, the best thing you can do is try the modules.

**Comment by pedrobaeza** [comment]
@flotho in services companies like ours, project management can be enough as we only have tasks for expressing an "issue", but in other type of companies, you can have RMAs, delivery issues, invoices with bad prices issues (this can happen also in services companies), etc. Having a common hub for handling them and then redirect to the proper "solver" is IMO the main goal of this module.

In my mind, the roadmap is to develop links to specific places:

* `helpdesk_mgmt_project`, that allows to create a task from the issues for using that task in classical project management (with duration, start date, deadline...), and maybe sync project stages with helpdesk stages.
* `helpdesk_mgmt_rma`, for linking with rma, but first we need a similar agreement like this for RMA :rofl: 
* `helpdesk_mgmt_...`

**Comment by flotho** [comment]
Hi @pedrobaeza @dxnacho ,

Thanks for your comments. 

Actually, some of my customers have this kinds of needs so @pedrobaeza I totally understood what you meant.
Yet I'm wondering if improving project management wouldn't be enough instead of adding helpdesk_mgmt_project.
But anyway, your answers are clear enough to understand what are the main next steps of this repo.

Regards
